<?php

/* @begin Configuration */
function MYMODULE_block_info() {
  $blocks = array();
  $blocks['trainers'] = array(
    'info' => 'Trainers',
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['employees'] = array(
    'info' => 'Employees',
    'cache' => DRUPAL_NO_CACHE,
  );  
  $blocks['partners'] = array(
    'info' => 'Partners',
    'cache' => DRUPAL_NO_CACHE,
  );  
  return $blocks;
}

function MYMODULE_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'trainers':
      $block['subject'] = 'For Trainees';
      $block['content'] = bricks_block_content($delta);
      break;
    case 'employees':
      $block['subject'] = 'For Employers';
      $block['content'] = bricks_block_content($delta);
      break;
    case 'partners':
      $block['subject'] = 'For Partners';
      /* For custom content functions */
      $block['content'] = MYMODULE_block_content($delta);
      break;
  }
  return $block;
}

/* Implements hook_block_default_content */
/* From the Bricks module */

function MYMODULE_block_default_content($delta) {
  $default = array();
  switch($delta) {
    case 'trainers':
      $default = array(
        'subtitle' => 'Duis mollis, eget lacinia odio sem nec',
        'body' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam quis risus eget urna mollis. ac consectetur ac, vestibulum at eros.',
      );
      break;
    case 'employees':
      $default = array(
        'subtitle' => 'Duis mollis, eget lacinia odio sem nec',
        'body' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam quis risus eget urna mollis. ac consectetur ac, vestibulum at eros.',
      );
      break;
    case 'partners':
      $default = array(
        'subtitle' => 'Duis mollis, eget lacinia odio sem nec',
        'body' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam quis risus eget urna mollis. ac consectetur ac, vestibulum at eros.',
      );
      break;

  }
  return $default;
}
/* @end Configuration */


/* @begin Logic */
function MYMODULE_block_configure($delta = '') {
  $form = array();
  switch($delta) {
    case '':
      /* This is where you can write custom handlers, which may or may not fall back on the Bricks functions */    
      break;
    case '':
      /* You can use the bricks functions to load up a form, then do custom modifications to the form */
      // $form = bricks_block_configure($delta);
      // $form['body']['#type'] = 'textarea';
      // $form['image'] = array(
      //   '#title' => t('Image'),
      //   '#type' => 'managed_file',
      //   '#description' => t('The uploaded image will be displayed on this page using the image style choosen below.'),
      //   '#upload_location' => 'public://MYMODULE/images/',
      //   '#default_value' => bricks_get($delta, 'image')
      // );      
      break;
    default:
      /* This loads the defaults, and creates a form from them. */
      /* If you need extra fields, you can add them in the defaults area, and they will be automatically added here. */
      $form = bricks_block_configure($delta);
      break;
  }
  return $form;
}

function MYMODULE_block_save($delta = '', $edit = array()) {
  switch($delta) {
    case '':
      /* This is where you can write custom handlers, which may or may not fall back on the Bricks functions */
      
      /* Handler for image function */

      // if(isset($edit['image']) && is_numeric($edit['image']) && $edit['image'] > 0) {
      //   $file = file_load($edit['image']);
      //   $file->status = FILE_STATUS_PERMANENT;
      //   file_save($file);
      //   file_usage_add($file, 'MYMODULE', 'node', 1); // Homepage $nid
      // }

      // bricks_block_save($delta, $edit);
      break;
    default:
      /* This simply runs through the submitted form, and saves all the content into appropriate variables */
      /* Unless you've got odd needs, there shouldn't be much reason to do anything else */
      bricks_block_save($delta, $edit);
      break;
  }
}
/* @end Logic */



/* ONLY NEEDED FOR CUSTOM CONTENT HANDLERS */
function MYMODULE_block_content($delta) {
  $block_array = bricks_block_load($delta);

  /* Do custom handling here */
  $image_id = bricks_get($delta, 'image');
  $image = file_load($image_id);
  $image_url = file_create_url($image->uri);  

  $block_array['image'] = $image_url;
  // or
  $block_array['image'] = '<img src="' . $image_url '" />';

  $html = bricks_array_to_html($block_array);  
  return $html;  
}