<?php

/* @begin Configuration */
function MYMODULE_block_info() {
  $blocks = array();
  $blocks['trainers'] = array(
    'info' => 'Trainers',
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['employees'] = array(
    'info' => 'Employees',
    'cache' => DRUPAL_NO_CACHE,
  );  
  $blocks['partners'] = array(
    'info' => 'Partners',
    'cache' => DRUPAL_NO_CACHE,
  );  
  return $blocks;
}

function MYMODULE_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'trainers':
      $block['subject'] = 'For Trainees';
      $block['content'] = MYMODULE_block_content($delta);
      break;
    case 'employees':
      $block['subject'] = 'For Employers';
      $block['content'] = MYMODULE_block_content($delta);
      break;
    case 'partners':
      $block['subject'] = 'For Partners';
      $block['content'] = MYMODULE_block_content($delta);
      break;
  }
  return $block;
}

/* Implements hook_variable_default_content */
function MYMODULE_block_default_content($delta) {
  $default = array();
  switch($delta) {
    case 'trainers':
      $default = array(
        'subtitle' => 'Duis mollis, eget lacinia odio sem nec',
        'body' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam quis risus eget urna mollis. ac consectetur ac, vestibulum at eros.',
      );
      break;
    case 'employees':
      $default = array(
        'subtitle' => 'Duis mollis, eget lacinia odio sem nec',
        'body' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam quis risus eget urna mollis. ac consectetur ac, vestibulum at eros.',
      );
      break;
    case 'partners':
      $default = array(
        'subtitle' => 'Duis mollis, eget lacinia odio sem nec',
        'body' => 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Nullam quis risus eget urna mollis. ac consectetur ac, vestibulum at eros.',
      );
      break;

  }
  return $default;
}
/* @end Configuration */


/* @begin Logic */
function MYMODULE_block_configure($delta = '') {
  $form = array();
  switch($delta) {
    default:
      $form = bricks_block_form($delta);
      break;
  }
  return $form;
}

function MYMODULE_block_save($delta = '', $edit = array()) {
  switch($delta) {
    default:
      bricks_block_save($delta, $edit);
      break;
  }
}

function MYMODULE_block_content($delta) {
  $html = '';
  switch($delta) {
    default:
      $html = bricks_block_html($delta);
      break;
  }
  return $html;
}
/* @end Logic */


